baseURL = "/"
languageCode = 'fr-fr'
title = 'GdR GPL'
theme = "mon-theme"
canonifyURLs = true

[taxonomies]
  archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


